name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [ '17' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: --info --stacktrace build jlink
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: KoreNG-jdk${{ matrix.java }}-${{ matrix.os }}
          path: build/image/*
